set(sources_tmp
    DockAreaTabBar.cpp
    DockAreaTabBar.h
    DockAreaTitleBar.cpp
    DockAreaTitleBar.h
    DockAreaTitleBar_p.h
    DockAreaWidget.cpp
    DockAreaWidget.h
    DockComponentsFactory.cpp
    DockComponentsFactory.h
    DockContainerWidget.cpp
    DockContainerWidget.h
    DockGroupMenu.cpp
    DockGroupMenu.h
    DockManager.cpp
    DockManager.h
    DockOverlay.cpp
    DockOverlay.h
    DockSplitter.cpp
    DockSplitter.h
    DockWidget.cpp
    DockWidget.h
    DockWidgetTab.cpp
    DockWidgetTab.h
    DockingStateReader.cpp
    DockingStateReader.h
    ElidingLabel.cpp
    ElidingLabel.h
    FloatingDockContainer.cpp
    FloatingDockContainer.h
    FloatingDragPreview.cpp
    FloatingDragPreview.h
    IconProvider.cpp
    IconProvider.h
    ads.qrc
    ads_globals.cpp
    ads_globals.h
    stylesheets/default.css
    stylesheets/default_linux.css
    )
